version: '3'

services:

  vault:
    image: hashicorp/vault:latest
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_CONFIG='{"ui":true,"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":"true"}},"backend":{"file":{"path":"/vault/file"}},"default_lease_ttl":"168h","max_lease_ttl":"0h","api_addr":"http://0.0.0.0:8200"}'
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json